/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Facade;
import Model.Registro;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author nous_
 */
public class Admin extends javax.swing.JFrame {
        private Facade facade;
    /**
     * Creates new form RecuperarContraseña
     */
    public Admin() {
        this.facade = new Facade();
        initComponents();
        facade = new Facade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultarRegistros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        REGISTROS = new javax.swing.JTextArea();
        LabelBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsultarRegistros.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultarRegistros.setText("Consultar Registros");
        btnConsultarRegistros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarRegistrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 30));

        REGISTROS.setColumns(20);
        REGISTROS.setRows(5);
        jScrollPane1.setViewportView(REGISTROS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 560, 330));

        LabelBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paper.png"))); // NOI18N
        getContentPane().add(LabelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, 0, 1220, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarRegistrosActionPerformed
        try{
            
            Registro registros = facade.getAllRegistros();
            
            String modificador = registros.getModificador();
            String libro = registros.getLibro();
            String id = registros.getId();
           
            REGISTROS.setText("modificador: "  + modificador + "\n" + "Titulo libro: " + libro + "\n" + "id: " + id);
        }catch (Exception e) {
            // Muestra el error en una ventana emergente
            JOptionPane.showMessageDialog(null, "Se produjo un error: " + e.getMessage(), "No se pudo generar los registros", JOptionPane.ERROR_MESSAGE);
        }finally {
            // Este bloque siempre se ejecuta
            
        
      
      }
    }//GEN-LAST:event_btnConsultarRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LabelBienvenida;
    private javax.swing.JTextArea REGISTROS;
    public javax.swing.JButton btnConsultarRegistros;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
