/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author nous_
 */
public class GestorDocumentos extends javax.swing.JFrame {

    /**
     * Creates new form GestorDocumentos
     */
    public GestorDocumentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEditorial = new javax.swing.JTextField();
        txtTotalPaginas = new javax.swing.JTextField();
        txtFechaPublicacion = new javax.swing.JTextField();
        txtISBNSNN = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtEstadoDocumento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPonencias = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAutores = new javax.swing.JTextArea();
        comboboxFiltros = new javax.swing.JComboBox<>();
        btnConsultarTablaMods = new javax.swing.JButton();
        comboboxDocumentos = new javax.swing.JComboBox<>();
        btnCerrarSesion = new javax.swing.JButton();
        btnDevolverDocumento = new javax.swing.JButton();
        btnReservarDocumento = new javax.swing.JButton();
        btnConsultarDoc = new javax.swing.JButton();
        btnAplicarFiltro = new javax.swing.JButton();
        btnCrearDocumento = new javax.swing.JButton();
        btnModificarDocumento = new javax.swing.JButton();
        btnEliminarDocumento = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEditorial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEditorial.setText("Editorial");
        txtEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialActionPerformed(evt);
            }
        });
        getContentPane().add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 210, -1));

        txtTotalPaginas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPaginas.setText("Total de Paginas");
        txtTotalPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPaginasActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, -1));

        txtFechaPublicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaPublicacion.setText("ISBN / SNN");
        txtFechaPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaPublicacionActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, -1));

        txtISBNSNN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtISBNSNN.setText("Fecha de Publicacion");
        txtISBNSNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNSNNActionPerformed(evt);
            }
        });
        getContentPane().add(txtISBNSNN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 210, -1));

        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitulo.setText("Titulo del Documento");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 210, -1));

        txtEstadoDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstadoDocumento.setText("Estado de Documento");
        txtEstadoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstadoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 210, -1));

        txtPonencias.setColumns(20);
        txtPonencias.setRows(5);
        txtPonencias.setText("Ponencias");
        jScrollPane2.setViewportView(txtPonencias);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 310, 240));

        txtAutores.setColumns(20);
        txtAutores.setRows(5);
        txtAutores.setText("Autores");
        jScrollPane1.setViewportView(txtAutores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 310, 230));

        comboboxFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboboxFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 20));

        btnConsultarTablaMods.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultarTablaMods.setText("Consultar Modificaciones");
        btnConsultarTablaMods.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnConsultarTablaMods, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 180, -1));

        comboboxDocumentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboboxDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 210, -1));

        btnDevolverDocumento.setBackground(new java.awt.Color(204, 204, 255));
        btnDevolverDocumento.setText("Devolucion");
        btnDevolverDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnDevolverDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, -1));

        btnReservarDocumento.setBackground(new java.awt.Color(204, 204, 255));
        btnReservarDocumento.setText("Reservar Online");
        btnReservarDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnReservarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, -1));

        btnConsultarDoc.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultarDoc.setText("Consultar Documento");
        btnConsultarDoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnConsultarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        btnAplicarFiltro.setBackground(new java.awt.Color(204, 204, 255));
        btnAplicarFiltro.setText("Aplicar Filtro");
        btnAplicarFiltro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnAplicarFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        btnCrearDocumento.setBackground(new java.awt.Color(204, 204, 255));
        btnCrearDocumento.setText("Crear Documento");
        btnCrearDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearDocumentoMouseClicked(evt);
            }
        });
        getContentPane().add(btnCrearDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, -1));

        btnModificarDocumento.setBackground(new java.awt.Color(204, 204, 255));
        btnModificarDocumento.setText("Modificar Documento");
        btnModificarDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnModificarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 180, -1));

        btnEliminarDocumento.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminarDocumento.setText("Eliminar Documento");
        btnEliminarDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnEliminarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 180, -1));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paper.png"))); // NOI18N
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtFechaPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPublicacionActionPerformed

    private void txtISBNSNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNSNNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNSNNActionPerformed

    private void txtTotalPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPaginasActionPerformed

    private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialActionPerformed

    private void txtEstadoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoDocumentoActionPerformed

    private void btnCrearDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearDocumentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorDocumentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LabelFondo;
    public javax.swing.JButton btnAplicarFiltro;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnConsultarDoc;
    public javax.swing.JButton btnConsultarTablaMods;
    public javax.swing.JButton btnCrearDocumento;
    public javax.swing.JButton btnDevolverDocumento;
    public javax.swing.JButton btnEliminarDocumento;
    public javax.swing.JButton btnModificarDocumento;
    public javax.swing.JButton btnReservarDocumento;
    public javax.swing.JComboBox<String> comboboxDocumentos;
    public javax.swing.JComboBox<String> comboboxFiltros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea txtAutores;
    public javax.swing.JTextField txtEditorial;
    public javax.swing.JTextField txtEstadoDocumento;
    public javax.swing.JTextField txtFechaPublicacion;
    public javax.swing.JTextField txtISBNSNN;
    public javax.swing.JTextArea txtPonencias;
    public javax.swing.JTextField txtTitulo;
    public javax.swing.JTextField txtTotalPaginas;
    // End of variables declaration//GEN-END:variables
}
